#!/bin/bash

# display impacket commands for priv-esc

Frame='\033[0;32m'   # Green
Link='\033[0;35m'  	 # Purple
Title='\033[1;33m' 	 # Bold Yellow
Comment='\033[0;36m' # Cyan
End='\033[0m'		 # No Color
Point='\033[0;31m[*]\033[0m'

echo -e "${Frame}###${End} ${Title}Impacket-SMBExec${End} ${Frame}###${End}"
echo -e "${Point} impacket-smbexec domain.local/\$user:\$password@\$IP"
echo -e ""
