#!/bin/bash

# display commands for manual windows local enumeration

Frame='\033[0;32m'   # Green
Link='\033[0;35m'  	 # Purple
Title='\033[1;33m' 	 # Bold Yellow
Comment='\033[0;36m' # Cyan
End='\033[0m'		 # No Color
Point='\033[0;31m[*]\033[0m'

echo -e "${Frame}###${End} ${Title}System Info Enum${End} ${Frame}###${End}"
echo -e "${Point} systeminfo | findstr /B /C:\"OS Name\" /C:\"OS Version\" ${Comment}# os name & version${End}"
echo -e "${Point} wmic os get osarchitecture || echo %PROCESSOR_ARCHITECTURE% ${Comment}# system architecture${End}"
echo -e "${Point} wmic qfe get Caption,Description,HotFixID,InstalledOn ${Comment}# patches${End}"
echo -e ""


echo -e "${Frame}###${End} ${Title}AlwaysInstallElevated${End} ${Frame}###${End}"
echo -e "${Point} reg query HKCU\\\SOFTWARE\\\Policies\\\Microsoft\\\Windows\\\Installer /v AlwaysInstallElevated"
echo -e "${Point} reg query HKLM\\\SOFTWARE\\\Policies\\\Microsoft\\\Windows\\\Installer /v AlwaysInstallElevated"
echo -e ""




